### ISSUE TITLE
@Scheduled annotation not working in the dummy Producer

### ISSUE THREAD

**Issue by guille** [Arquisoft/dashboard_i3b#7]
The methods send() and send2() in the MessageProducer class are never getting executed

**Comment by juanfadev** [comment]
Solved creating a new project where scheduling worked good and import all maven libraries and all classes. Now it works good. Uploaded on commit https://github.com/Arquisoft/dashboard_i3b/commit/e68b35e4ae28ab798f340a919410096b7dc2dd84
