### ISSUE TITLE
Route "/" displays a json

### ISSUE THREAD

**Issue by guille** [Arquisoft/dashboard_i3b#9]
After running the application and accessing localhost:8090, the page displayed isn't the index.html template

![Screenshot attached](https://cloud.githubusercontent.com/assets/1296511/24471795/8deeb044-14c3-11e7-846b-0f18be6426b1.png)

**Comment by juanfadev** [comment]
Solved when scheduling done good. On commit https://github.com/Arquisoft/dashboard_i3b/commit/e68b35e4ae28ab798f340a919410096b7dc2dd84
